language: python

cache: pip

python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "pypy"
    - "nightly"

install:
    - pip install pipenv==2018.7.1
    - pipenv install --dev --system

script:
    - pytest --cov pypexels --cov-report term-missing --cov-report xml

after_success:
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    # codecov  # python specific?

